import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  background: {
    position: 'absolute',
    width: '50%',
    height: '50%',
    right: 0,
  },
  container: {
    flex: 1,
  },
  containerImage: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
  },
  containerList: {
    flex: 2,
  },
  imageCenter: {
    width: '100%',
    height: '100%',
  },
  title: {
    fontSize: 20,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    width: '100%',
    textAlign: 'center',
    color: '#FF725EC7',
  },
  itemsList: {
    flex: 1,
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
  },
  item: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    width: '80%',
    marginBottom: 20,
  },
  itemText: {
    color: '#4A4A4A',
    fontSize: 20,
    fontWeight: '500',
    width: '100%',
    textAlign: 'center',
  },
  addBtn: {
    position: 'absolute',
    right: 20,
    bottom: 50,
    backgroundColor: '#FF725E',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 30,
    alignItems: 'center',
  },
  addBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  wifiSelectorBtn: {
    position: 'absolute',
    left: 20,
    top: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    zIndex: 9,
  },
});
